- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update-cache: yes

- name: Overwrite default config file
  copy: 
    src: default
    dest: /etc/nginx/sites-enabled/default
    mode: 0644
  notify: Restart Nginx

- name: Nginx service
  service:
    name: nginx
    state: started
    enabled: yes