- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update-cache: yes

- name: Change index page
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.nginx-debian.html
