- name: Install HAProxy
  apt:
    name: haproxy

- name: HAProxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - Restart haproxy

- name: HAProxy service
  service:
    name: haproxy
    state: started