- name: Repository key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    update_cache: yes

- name: Install Grafana
  apt:
    name: grafana
  notify: Grafana password

- name: Grafana service
  service:
    name: grafana-server
    state: started
    enabled: yes

- name: grafana.ini
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart grafana

- name: Datasource
  ansible.builtin.copy:
    src: datasource.yaml
    dest: /etc/grafana/provisioning/datasources/sample.yaml
  notify: Restart grafana

- name: Dashboard
  ansible.builtin.copy:
    src: dashboard.yaml
    dest: /etc/grafana/provisioning/dashboards/sample.yaml
  notify: Restart grafana

- name: Dashboard template
  ansible.builtin.copy:
    src: dash.json
    dest: /var/lib/grafana/dashboards/
  notify: Restart grafana