---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init
    - node_exporter
    - rsyslog
    - backup
  tags: i

- name: DNS servers
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: b

- name: Resolv.conf file
  hosts: all
  become: yes
  roles:
    - resolver

- name: Database and DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
  tags: m

- name: Nginx
  hosts: all
  become: yes
  roles:
    - nginx
    - nginx_exporter
  tags: ng

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
  tags: w

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  roles:
    - prometheus
  tags: p

- name: Grafana
  hosts: grafana_servers
  become: yes
  roles:
    - grafana
  tags: g

- name: InfluxDB
  hosts: influxdb_servers
  become: yes
  roles:
    - influxdb
    - influxdb_exporter
  tags: flux

- name: Pinger
  hosts: pinger_servers
  become: yes
  roles:
    - pinger
  tags: ping
