---
- name: Init
  hosts: all
  become: yes
  roles:
    - init
    - systemd

- name: Database and DNS server
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - bind

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
