---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init
    - node_exporter

- name: Database and DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - bind

- name: Resolv.conf file
  hosts: all
  become: yes
  roles:
    - resolver

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
  tags: n

- name: Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus
  tags: p
