---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init
    - node_exporter
    - rsyslog
    - backup
  tags: always

- name: DNS servers
  hosts: dns_servers
  become: yes
  roles:
    - bind
    - bind_exporter
  tags: b

- name: Resolv.conf file
  hosts: all
  become: yes
  roles:
    - resolver

- name: MySQL
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - mysql_exporter
    - mysql_backup
  tags: m

- name: Prometheus
  hosts: prometheus_servers
  become: yes
  roles:
    - prometheus
    - nginx
    - nginx_exporter
  tags: p

- name: Docker
  hosts: docker_servers
  become: yes
  roles:
    - docker
  tags: d

- name: Agama
  hosts: web_app
  become: yes
  roles:
    - agama
    - nginx
    - nginx_exporter
  tags: w

- name: Grafana
  hosts: grafana_servers
  become: yes
  roles:
    - grafana
    - nginx
    - nginx_exporter
  tags: g

- name: Haproxy and keepalived
  hosts: haproxy_servers
  become: yes
  roles:
    - haproxy
    - haproxy_exporter
    - keepalived
    - keepalived_exporter
  tags: h

- name: InfluxDB
  hosts: influxdb_servers
  become: yes
  roles:
    - influxdb
    - influxdb_exporter
    - influxdb_backup
  tags: flux

- name: Pinger
  hosts: pinger_servers
  become: yes
  roles:
    - pinger
  tags: ping
