---
- name: Init
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - init

- name: Database and DNS server
  hosts: db_servers
  become: yes
  roles:
    - mysql
    - bind

- name: Resolv.conf file
  hosts: all
  become: yes
  roles:
    - resolver

- name: Web server
  hosts: web_servers
  become: yes
  roles:
    - agama
    - uwsgi
    - nginx
