- name: Create user agama
  ansible.builtin.user:
    name: agama
    state: present

- name: Create directory /opt/agama
  ansible.builtin.file:
    path: /opt/agama
    state: directory
    owner: agama

- name: Install application dependencies
  ansible.builtin.apt:
    name: 
    - python3-flask-sqlalchemy
    - python3-pymysql

- name: Install the agama application
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hudolejev/agama/master/agama.py
    dest: /opt/agama
