- name: Create a directory for user backup
  ansible.builtin.file:
    path: /home/backup/influxdb
    state: directory
    owner: backup

- name: InfluxDB crontab                                                           
  ansible.builtin.template:                                                     
    src: influxdb-backup.j2                                              
    dest: /etc/cron.d/influxdb-backup