- name: Upload keepalived exporter file
  ansible.builtin.unarchive:
    src: http://backup/keepalived-exporter-1.2.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
  notify: Restart keepalived-exporter

- name: Copy keepalived-exporter.service
  ansible.builtin.copy:
    src: keepalived-exporter.service
    dest: /etc/systemd/system/prometheus-keepalived-exporter.service
  notify: 
    - Reload daemons
    - Restart keepalived-exporter

- name: Keepalived-exporter service
  ansible.builtin.service:
    name: prometheus-keepalived-exporter
    state: started
    enabled: yes