- name: Install Bind package
  apt:
    name: 
      - bind9
      - python3-dnspython

- name: Check service bind9
  service:
    name: bind9
    state: started

- name: Overwrite named.conf.options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Overwrite named.conf.local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Create db of the startup
  template:
    src: db.nicole.ta.j2
    dest: /var/cache/bind/db.nicole.ta
    force: no
  notify: Reload db
  when: inventory_hostname in groups['dns_masters']

- name: Create db of the reverse
  template:
    src: db.reverse.j2
    dest: /var/cache/bind/db.reverse
  notify: Reload db
  when: inventory_hostname in groups['dns_masters']

