- name: Install Bind package
  apt:
    name: bind9

- name: Check service bind9
  service:
    name: bind9
    state: started

- name: Overwrite resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Overwrite named.conf.options file
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind9

- name: Overwrite named.conf.local file
  template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
  notify: Restart bind9

- name: Create db of the startup
  template:
    src: db.nicole.ptr.j2
    dest: /var/lib/bind/db.nicole.ptr
  notify: Reload db